/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2022-07-20-1a69da0824"
#endif /* AVUTIL_FFVERSION_H */
