/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2022-09-06-c578f7ebdc"
#endif /* AVUTIL_FFVERSION_H */
