/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2022-09-08-305f19ceb6"
#endif /* AVUTIL_FFVERSION_H */
